# -*- coding: utf-8 -*-
"""
PPMS VSM(.dat) から VSM(.VSM) 形式へ変換するプログラム (文字コード修正版)

このプログラムを実行すると、ファイル選択ウィンドウが開きます。
1. 最初に、変換したいPPMSの.datファイルを選択します。
2. 次に、変換後の.VSMファイルを保存する場所と名前を指定します。
3. 変換が実行され、指定した場所に.VSMファイルが作成されます。
"""

import pandas as pd
from datetime import datetime, timedelta
import tkinter as tk
from tkinter import filedialog, messagebox
import os

def convert_dat_to_vsm(dat_file_path, vsm_file_path):
    """
    Quantum DesignのPPMS VSMから出力された.datファイルを.VSM形式に変換するコア関数。

    Args:
        dat_file_path (str): 入力となる.datファイルのパス。
        vsm_file_path (str): 出力となる.VSMファイルのパス。
    """
    # --- ステップ1: .datファイルの解析 ---
    header_info = {}
    data_lines = []
    is_data_section = False
    data_header = []

    try:
        #【修正点】文字コードを 'utf-8' から 'cp932' に変更しました。
        with open(dat_file_path, 'r', encoding='cp932') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                if line == '[Header]':
                    continue
                if line == '[Data]':
                    is_data_section = True
                    continue
                
                if not is_data_section:
                    parts = line.split(',')
                    if len(parts) > 1:
                        header_info[parts[0]] = parts[1:]
                else:
                    if not data_header:
                        data_header = [h.strip() for h in line.split(',')]
                    else:
                        data_lines.append([d.strip() for d in line.split(',')])
    except Exception as e:
        raise IOError(f".datファイルの読み込み中にエラーが発生しました: {e}")

    if not data_lines:
        raise ValueError(".datファイルにデータが見つかりませんでした。")

    df = pd.DataFrame(data_lines, columns=data_header)

    required_cols = ['Magnetic Field (Oe)', 'Moment (emu)', 'Time Stamp (sec)']
    for col in required_cols:
        if col not in df.columns:
            raise ValueError(f"必須列 '{col}' が.datファイルに見つかりません。")
            
    df = df[required_cols]
    df = df.apply(pd.to_numeric, errors='coerce')
    df.dropna(inplace=True)

    # --- ステップ2: .VSMヘッダー情報の準備 ---
    try:
        file_open_time_parts = header_info.get('FILEOPENTIME', [])
        date_str = file_open_time_parts[1]
        time_str = file_open_time_parts[2]
        start_datetime = datetime.strptime(f"{date_str} {time_str}", "%m/%d/%Y %I:%M %p")
        vsm_date = start_datetime.strftime("%Y/%m/%d")
        vsm_time = start_datetime.strftime("%H:%M:%S")
    except (IndexError, ValueError):
        start_datetime = datetime.now() # Fallback
        vsm_date = start_datetime.strftime("%Y/%m/%d")
        vsm_time = start_datetime.strftime("%H:%M:%S")

    sample_name = header_info.get('TITLE', [''])[0].strip() or os.path.basename(dat_file_path).replace('.dat', '')
    
    meas_points = len(df)
    max_magnetic_field = df['Magnetic Field (Oe)'].abs().max()
    max_magnetization = df['Moment (emu)'].abs().max()
    
    time_stamps = df['Time Stamp (sec)']
    measuring_time_min = (time_stamps.iloc[-1] - time_stamps.iloc[0]) / 60 if meas_points > 1 else 0

    # --- ステップ3: .VSMファイルの書き込み ---
    with open(vsm_file_path, 'w', encoding='utf-8') as f:
        # ヘッダー生成
        f.write("version=,vbvsm-1.00DATE\n")
        f.write(f"date=,{vsm_date}\n")
        f.write(f"time,{vsm_time}\n")
        f.write(f"sample name=,{sample_name}\n")
        f.write("comment=,\n")
        f.write("file pattern=,custum\n")
        f.write("meas. seq. filename=,(generated by script)\n")
        f.write("correction(demagnetization field)=,NO\n")
        f.write("correction(diamagnetism)=,NO\n")
        f.write("correction(subtraction)=,NO\n")
        f.write("correction(addition)=,NO\n")
        f.write("correction(spline)=,NO\n")
        f.write("correction(smoothing)=,NO\n")
        f.write("correction(image effect)=,NO\n")
        f.write("sweep or plot measurement=,custum\n")
        f.write("lock-in amp. sensitivity=,0.02,(mV)\n")
        f.write("lock-in amp. time constant=,100,(msec)\n")
        f.write(f"sample volume=,{header_info.get('SAMPLE_VOLUME', ['0'])[0]},(cc)\n")
        f.write(f"sample weight=,{header_info.get('SAMPLE_MASS', ['0'])[0]},(g)\n")
        f.write("magnet angle=,0,(degree)\n")
        f.write("temperature(max)=,-300,(ßC)\n")
        f.write(f"measuring points=,{meas_points}\n")
        f.write(f"max magnetic field=,{max_magnetic_field:.4f},(Oe)\n")
        f.write(f"max magnetization=,{max_magnetization:.4E},(emu)\n")
        f.write("segment management=,,\n")
        f.write("lock-in amp. phase=,-43.27,(degree)\n")
        f.write("pole piece gap=,30,(mm)\n")
        f.write("diamagnetism value (a)=,0\n")
        f.write("diamagnetism value (b)=,0\n")
        f.write("calibration value=,0.07918\n")
        f.write(f"measuring time=,{measuring_time_min:.2f},(min)\n")
        f.write("sample thickness=,0,(nm)\n")
        f.write("Sample Area=,0,(cm2)\n")
        f.write("demagnetization factor=,0,(CGS)\n")
        
        # 6行の空行
        for _ in range(6):
            f.write(",,\n")
            
        # データヘッダー
        f.write("Date,H(Oe),M(emu),Angle(degree)\n")
        
        # データ行
        time_offset = time_stamps.iloc[0]
        for index, row in df.iterrows():
            current_time = start_datetime + timedelta(seconds=(row['Time Stamp (sec)'] - time_offset))
            date_time_str = current_time.strftime("%Y/%m/%d %H:%M:%S")
            h_oe = row['Magnetic Field (Oe)']
            m_emu = row['Moment (emu)']
            angle = 90.0
            
            f.write(f"{date_time_str},{h_oe:.2f},{m_emu:.4E},{angle:.1f}\n")

def main():
    """
    ファイルダイアログを開き、変換プロセスを実行するメイン関数。
    """
    root = tk.Tk()
    root.withdraw()

    messagebox.showinfo("ステップ1", "変換したい.datファイルを選択してください。")
    dat_path = filedialog.askopenfilename(
        title="変換する.datファイルを選択",
        filetypes=(("DAT files", "*.dat"), ("All files", "*.*"))
    )
    if not dat_path:
        print("ファイル選択がキャンセルされました。")
        return

    default_vsm_name = os.path.basename(dat_path).replace('.dat', '.vsm').replace('.DAT', '.vsm')
    messagebox.showinfo("ステップ2", "変換後の.VSMファイルの保存場所と名前を指定してください。")
    vsm_path = filedialog.asksaveasfilename(
        title="VSMファイルの保存先",
        initialfile=default_vsm_name,
        defaultextension=".vsm",
        filetypes=(("VSM files", "*.vsm"), ("All files", "*.*"))
    )
    if not vsm_path:
        print("保存先指定がキャンセルされました。")
        return

    try:
        print(f"変換中: {dat_path} -> {vsm_path}")
        convert_dat_to_vsm(dat_path, vsm_path)
        print(f"✅ 変換完了: {vsm_path}")
        messagebox.showinfo("成功", f"変換が完了しました。\nファイルは以下に保存されました:\n{vsm_path}")
    except Exception as e:
        print(f"❌ エラー発生: {e}")
        messagebox.showerror("エラー", f"変換中にエラーが発生しました:\n{e}")

if __name__ == "__main__":
    main()